#!/bin/bash -xe
export RUNTIME_DIRECTORY=$(dirname "$0")/../tmp/run

unset AWS_PROFILE
unset AWS_DEFUALT_PROFILE
export AWS_CONFIG_FILE=${RUNTIME_DIRECTORY}/unexist
export AWS_SHARED_CREDENTIALS_FILE=${RUNTIME_DIRECTORY}/unexist2
unset AWS_CONTAINER_CREDENTIALS_FULL_URI
unset AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
unset AWS_CONTAINER_AUTHORIZATION_TOKEN
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
export AWS_EC2_METADATA_DISABLED=true

cargo run -- bind myrole --url http://127.0.0.1:3000 "$@"

. "${RUNTIME_DIRECTORY}/env/myrole"
export AWS_CONTAINER_CREDENTIALS_FULL_URI
export AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
export AWS_CONTAINER_AUTHORIZATION_TOKEN

export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-1}
aws sts get-caller-identity --debug | cat
